export const removeWhiteSpace = (str) => {
    return str.replace(/\s/g,'');
};

// NOTE : This method will also remove the keys from your object, which have
// functions as their values, because the JSON doesn't support functions.
// Date objects will also be converted back to UTC in the string representation
// in the ISO8601 format.
export const cloneDeep = (obj) => {
  return JSON.parse(JSON.stringify(obj));
};

export const getTemplateItems = () => {
  return [{"name":"Stockholm Pizza","address":"Scheelegatan 15, 112 28 Stockholm","hours":["10.00","21.00"],"tags":["Pizza","Kebab","Sallad"],"menu":{"sv":[{"name":"Kyckling","items":[{"name":"Kycklingtallrik","desc":"Kyckling, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås och pommes.","price":"90 SEK"},{"name":"Kycklingrulle","desc":"Kyckling, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås i pizzabröd.","price":"90 SEK"},{"name":"Kycklingsallad","desc":"Kyckling, isbergssallad, tomat, lök, fefferoni, tomatsås och vitlökssås.","price":"90 SEK"}]},{"name":"Kebab","items":[{"name":"Kebabtallrik","desc":"Kebab, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås och pommes.","price":"90 SEK"},{"name":"Kebabrulle","desc":"Kebab, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås i pizzabröd.","price":"90 SEK"},{"name":"Kebabsallad","desc":"Kebab, isbergssallad, tomat, lök, fefferoni, tomatsås och vitlökssås.","price":"90 SEK"}]},{"name":"Gyros","items":[{"price":"90 SEK","desc":"Gyros, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås och pommes.","name":"Gyrostallrik"},{"price":"90 SEK","desc":"Gyros, isbergssallad, tomat, lök, fefferoni, tomatsås, vitlökssås i pizzabröd.","name":"Gyrosrulle"},{"price":"90 SEK","desc":"Gyros, isbergssallad, tomat, lök, fefferoni, tomatsås och vitlökssås.","name":"Gyrossallad"}]}],"en":[{"name":"Chicken","items":[{"name":"Chicken plate","desc":"Chicken, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce and french fries.","price":"90 SEK"},{"name":"Chicken roll","desc":"Chicken, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce in pizza bread.","price":"90 SEK"},{"name":"Chicken salad","desc":"Chicken, salad, tomato, onion, fefferoni, tomato sauce and garlic sauce.","price":"90 SEK"}]},{"name":"Kebab","items":[{"name":"Kebab plate","desc":"Kebab, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce and french fries.","price":"90 SEK"},{"name":"Kebab roll","desc":"Kebab, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce in pizza bread.","price":"90 SEK"},{"name":"Kebab salad","desc":"Kebab, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce.","price":"90 SEK"}]},{"name":"Gyros","items":[{"price":"90 SEK","desc":"Gyros, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce and french fries.","name":"Gyros plate"},{"price":"90 SEK","desc":"Gyros, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce in pizza bread.","name":"Gyros roll"},{"price":"90 SEK","desc":"Gyros, salad, tomato, onion, fefferoni, tomato sauce, garlic sauce.","name":"Gyros salad"}]}]},"images":{"banner":"img/banner.png","gallery":"img/gallery.png"}}]
};
